### ISSUE TITLE
Thay đổi đề tài của nhóm

### ISSUE THREAD

**Issue by HoangTheThuong** [TeamCongNghePhanMem/HusShop#3]
Tình hình mới của nhóm: Một số thành viên trong nhóm có tham góp về đề tài hiện tại là nếu làm về game thì sẽ không phát huy được toàn bộ sức mạnh của cả team, vì hiểu biết về game còn hạn chế, một số bạn thậm chí chưa biết chơi và hạn chế về mặt ngôn ngữ sử dụng trong quá trình viết game. Ý kiến của các bạn là thay từ game sang web. Mọi người có tham góp  ý kiến gì không ? nên tiếp tục đề tài cũ hay chuyển đề tài làm Web?.  Và nếu chuyển thì có ý tưởng gì mới và phù hợp cho đề tài Web không?

**Comment by PhungVanSy** [comment]
t đề suất trang web bán hàng mùa đông mn thấy sao !

**Comment by HoangTheThuong** [comment]
mọi người có góp ý gì thì comment sớm nhé. Vì chúng ta phải đưa ra quyết định về đề tài sớm.

**Comment by QuangTrung96** [comment]
Theo em thì chúng ta làm web  trang bán sách hoặc trang web bán máy tính
Công nghệ sử dụng là PHP( framework: Larevel)

**Comment by HoangTheThuong** [comment]
Sau khi thống nhất các thành viên: Đề tài mới của nhóm mình sẽ là "Xây dựng một trang Web bán hàng quần áo thời trang nhé"

**Comment by DinhVanBinh** [comment]
Hay nhóm làm một cái ứng dụng gì đó trên điện thoại đi :)

**Comment by DinhVanBinh** [comment]
Đề tài có thể là tìm nhà trọ cho sinh viên hay gì đó nghe gần gũi với sinh viên hơn
